apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomizer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: randomizer
          image: jakubmi/randomizer
          ports:
            - containerPort: 8080
