apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomizer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomizer
  template:
    metadata:
      labels:
        app: randomizer
    spec:
      containers:
        - name: randomizer
          image: jakubmi/randomizer
          ports:
            - containerPort: 8080
