apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomizer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: randomizer
          image: jakubmi/randomizer:1.0
          ports:
            - containerPort: 4567
