apiVersion: v1
kind: Pod
metadata:
  name: randomizer-pod
  labels:
    component: web
spec:
  containers:
    - name: randomizer
      image: jakubmi/randomizer:1.0
      ports:
        - containerPort: 4567
