apiVersion: v1
kind: Pod
metadata:
  name: randomizer-pod
spec:
  containers:
    - image: jakubmi/randomizer
      name: randomizer
      resources:
        requests:
          cpu: "500m"
          memory: 128Mi
      ports:
        - containerPort: 8080
